language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
    - "~/.platformio"

install:
  - pip install -U platformio
  - platformio update

script:
  - platformio run
  - python ~/.platformio/packages/framework-arduinoespressif8266/tools/signing.py --mode sign --privatekey private.key --bin .pio/build/esp12e/firmware.bin --out .pio/build/signed.bin

deploy:
  - provider: script
    script: bash scripts/deploy.sh $TRAVIS_BUILD_NUMBER
    on:
      branch: master
