/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "logmessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LogMessage, LogMessage, 2)


PB_BIND(LogMessage_CardTransaction, LogMessage_CardTransaction, AUTO)


PB_BIND(LogMessage_Order, LogMessage_Order, 2)


PB_BIND(LogMessage_Order_CartItem, LogMessage_Order_CartItem, 2)





