/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_SRC_PROTO_TRANSACTION_PB_H_INCLUDED
#define PB_SRC_PROTO_TRANSACTION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _TransactionMessage_Mode {
    TransactionMessage_Mode_TIME_ENTRY = 0,
    TransactionMessage_Mode_TOP_UP = 1,
    TransactionMessage_Mode_CHARGE = 2,
    TransactionMessage_Mode_CASHOUT = 3,
    TransactionMessage_Mode_INIT_CARD = 4
} TransactionMessage_Mode;

/* Struct definitions */
typedef struct _CartItemMessage {
    int32_t price;
    char product[17];
} CartItemMessage;

typedef struct _TransactionMessage {
    char id[9];
    char device_id[40];
    TransactionMessage_Mode mode;
    int32_t device_time;
    char card[9];
    int32_t balanceBefore;
    int32_t tokensBefore;
    int32_t balanceAfter;
    int32_t tokensAfter;
    bool has_list_name;
    char list_name[17];
    pb_size_t cart_items_count;
    CartItemMessage cart_items[10];
} TransactionMessage;


/* Helper constants for enums */
#define _TransactionMessage_Mode_MIN TransactionMessage_Mode_TIME_ENTRY
#define _TransactionMessage_Mode_MAX TransactionMessage_Mode_INIT_CARD
#define _TransactionMessage_Mode_ARRAYSIZE ((TransactionMessage_Mode)(TransactionMessage_Mode_INIT_CARD+1))


/* Initializer values for message structs */
#define TransactionMessage_init_default          {"", "", _TransactionMessage_Mode_MIN, 0, "", 0, 0, 0, 0, false, "", 0, {CartItemMessage_init_default, CartItemMessage_init_default, CartItemMessage_init_default, CartItemMessage_init_default, CartItemMessage_init_default, CartItemMessage_init_default, CartItemMessage_init_default, CartItemMessage_init_default, CartItemMessage_init_default, CartItemMessage_init_default}}
#define CartItemMessage_init_default             {0, ""}
#define TransactionMessage_init_zero             {"", "", _TransactionMessage_Mode_MIN, 0, "", 0, 0, 0, 0, false, "", 0, {CartItemMessage_init_zero, CartItemMessage_init_zero, CartItemMessage_init_zero, CartItemMessage_init_zero, CartItemMessage_init_zero, CartItemMessage_init_zero, CartItemMessage_init_zero, CartItemMessage_init_zero, CartItemMessage_init_zero, CartItemMessage_init_zero}}
#define CartItemMessage_init_zero                {0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define CartItemMessage_price_tag                1
#define CartItemMessage_product_tag              2
#define TransactionMessage_id_tag                1
#define TransactionMessage_device_id_tag         2
#define TransactionMessage_mode_tag              3
#define TransactionMessage_device_time_tag       4
#define TransactionMessage_card_tag              5
#define TransactionMessage_balanceBefore_tag     6
#define TransactionMessage_tokensBefore_tag      7
#define TransactionMessage_balanceAfter_tag      8
#define TransactionMessage_tokensAfter_tag       9
#define TransactionMessage_list_name_tag         10
#define TransactionMessage_cart_items_tag        11

/* Struct field encoding specification for nanopb */
#define TransactionMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, STRING,   id,                1) \
X(a, STATIC,   REQUIRED, STRING,   device_id,         2) \
X(a, STATIC,   REQUIRED, UENUM,    mode,              3) \
X(a, STATIC,   REQUIRED, INT32,    device_time,       4) \
X(a, STATIC,   REQUIRED, STRING,   card,              5) \
X(a, STATIC,   REQUIRED, INT32,    balanceBefore,     6) \
X(a, STATIC,   REQUIRED, INT32,    tokensBefore,      7) \
X(a, STATIC,   REQUIRED, INT32,    balanceAfter,      8) \
X(a, STATIC,   REQUIRED, INT32,    tokensAfter,       9) \
X(a, STATIC,   OPTIONAL, STRING,   list_name,        10) \
X(a, STATIC,   REPEATED, MESSAGE,  cart_items,       11)
#define TransactionMessage_CALLBACK NULL
#define TransactionMessage_DEFAULT NULL
#define TransactionMessage_cart_items_MSGTYPE CartItemMessage

#define CartItemMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    price,             1) \
X(a, STATIC,   REQUIRED, STRING,   product,           2)
#define CartItemMessage_CALLBACK NULL
#define CartItemMessage_DEFAULT NULL

extern const pb_msgdesc_t TransactionMessage_msg;
extern const pb_msgdesc_t CartItemMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TransactionMessage_fields &TransactionMessage_msg
#define CartItemMessage_fields &CartItemMessage_msg

/* Maximum encoded size of messages (where known) */
#define TransactionMessage_size                  446
#define CartItemMessage_size                     29

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
