/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "transaction.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CardTransaction, CardTransaction, 2)


PB_BIND(CardTransaction_CartItem, CardTransaction_CartItem, 2)





