/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_CONFIG_PB_H_INCLUDED
#define PB_CONFIG_PB_H_INCLUDED
#include <pb.h>
#include "product.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _DeviceConfig {
    pb_callback_t name;
    int32_t list_id;
    pb_callback_t products;
    int32_t checksum;
} DeviceConfig;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DeviceConfig_init_default                {{{NULL}, NULL}, 0, {{NULL}, NULL}, 0}
#define DeviceConfig_init_zero                   {{{NULL}, NULL}, 0, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceConfig_name_tag                    1
#define DeviceConfig_list_id_tag                 2
#define DeviceConfig_products_tag                3
#define DeviceConfig_checksum_tag                4

/* Struct field encoding specification for nanopb */
#define DeviceConfig_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, INT32,    list_id,           2) \
X(a, CALLBACK, REPEATED, MESSAGE,  products,          3) \
X(a, STATIC,   SINGULAR, INT32,    checksum,          4)
#define DeviceConfig_CALLBACK pb_default_field_callback
#define DeviceConfig_DEFAULT NULL
#define DeviceConfig_products_MSGTYPE Product

extern const pb_msgdesc_t DeviceConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DeviceConfig_fields &DeviceConfig_msg

/* Maximum encoded size of messages (where known) */
/* DeviceConfig_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
