#include <MFRC522.h>

extern const int TOKEN_VALUE = 200;
const int TIMEZONE_OFFSET_MINUTES = 120;
const char* MODE_CHANGER = ENV_MODE_CHANGER;
const char* SALT = ENV_SALT;
MFRC522::MIFARE_Key KEY_B = {{ENV_KEY_B}};
const char* WIFI_SSID = ENV_WIFI_SSID;
const char* WIFI_PASSWORD = ENV_WIFI_PASSWORD;